### ISSUE TITLE
help

### ISSUE THREAD

**Issue by xiangfengzhuo** [midjji/ssba2016-scale-estimation#1]
can you provide some references to this code? I'm so  interested in this code

**Comment by midjji** [comment]
Huh?
What are you looking for?

It's really just a single formulae, the code is primarily an evaluation
toolkit.

**Comment by midjji** [comment]
Ill add the pub to archivex, tonight, but if you are at cvpr we can meet and I can show you

**Comment by xiangfengzhuo** [comment]
Thanks for your reply，i just want to know how to estmate the monocular visual odomery's absolute scale in your code.I have been doing research in this area recently, but there is no progress.

在 2018-06-19 00:14:25，"midjji" <notifications@github.com> 写道：
Huh?
What are you looking for?

It's really just a single formulae, the code is primarily an evaluation
toolkit.

**Comment by midjji** [comment]
Hi,
Ah unfortunately there is a misunderstanding,

The scale estimation in:

@inproceedings{persson2016metricscale,
  title={Metric scale with non-overlapping cameras, the 5+1 point method},
  author={Persson, Mikael and Robinson, Andreas},
  booktitle={Swedish Symposium on Image Analysis},
  year={2016}
}

also appended

Is about the case when you have cameras which are rigidly connected
and take images at the same time, but unlike eg stereo their fields of
view do not overlap.

The method is about a minimal case solver which is then refined by
bundleadjustment.

From a pure geometric standpoint, it is strictly impossible to
determine the true scale of a reconstruction from a single camera. T.
he scale simply cannot be inferred from the data available.

But if we assume we have additional knowledge about what is beeing
observed it is possible.

The simplest case is if say a chessboard pattern of known dimensions
is observed and identified. In this case we can propagate this scale
information throughout the posegraph, setting a true metric scale for
the entire reconstruction. Such a solution drifts however. In practice
the simplest thing to do is to use knowledge about some feature or
object which frequently occurs and use that. Back when i worked with
mono I used the license plates which in driving sequences are both
everywhere and of a strictly regulated size. Another common approach
is to use known camera placement relative to the road.

There are quite a few networks which output a depth map directly from
a single image. This is a generalization of the approach above which
combines object detection, known object size, common rigid 3D surfaces
and works by training on a large dataset of similar data. In general
they look like they almost work, but in practice they are terrible.
Essentially its much better to train on a million annotated licence
plates than use a few thousand images where most of the time the depth
cannot be inferred with accuracy at all. Since depth networks can be
trained in an unsupervised manner this might change, but its not quite
there yet.

In the end the best solution depends on your application,

what are you working on?


//Mikael


2018-06-20 8:59 GMT+02:00 xiangfengzhuo <notifications@github.com>:
